#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MiTerceraAppWeb
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="SistemaMatricula")]
	public partial class Miconexion3DataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Definiciones de métodos de extensibilidad
    partial void OnCreated();
    partial void InsertGradoSeccion(GradoSeccion instance);
    partial void UpdateGradoSeccion(GradoSeccion instance);
    partial void DeleteGradoSeccion(GradoSeccion instance);
    partial void InsertGrado(Grado instance);
    partial void UpdateGrado(Grado instance);
    partial void DeleteGrado(Grado instance);
    partial void InsertSeccion(Seccion instance);
    partial void UpdateSeccion(Seccion instance);
    partial void DeleteSeccion(Seccion instance);
    partial void InsertGrado1(Grado1 instance);
    partial void UpdateGrado1(Grado1 instance);
    partial void DeleteGrado1(Grado1 instance);
    #endregion
		
		public Miconexion3DataContext() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["SistemaMatriculaConnectionString"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public Miconexion3DataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public Miconexion3DataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public Miconexion3DataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public Miconexion3DataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<GradoSeccion> GradoSeccion
		{
			get
			{
				return this.GetTable<GradoSeccion>();
			}
		}
		
		public System.Data.Linq.Table<Grado> Grado
		{
			get
			{
				return this.GetTable<Grado>();
			}
		}
		
		public System.Data.Linq.Table<Seccion> Seccion
		{
			get
			{
				return this.GetTable<Seccion>();
			}
		}
		
		public System.Data.Linq.Table<Grado1> Grado1
		{
			get
			{
				return this.GetTable<Grado1>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.GradoSeccion")]
	public partial class GradoSeccion : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _IID;
		
		private System.Nullable<int> _IIDGRADO;
		
		private System.Nullable<int> _IIDSECCION;
		
		private System.Nullable<int> _BHABILITADO;
		
		private EntityRef<Grado> _Grado;
		
		private EntityRef<Seccion> _Seccion;
		
		private EntityRef<Grado1> _Grado1;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIIDChanging(int value);
    partial void OnIIDChanged();
    partial void OnIIDGRADOChanging(System.Nullable<int> value);
    partial void OnIIDGRADOChanged();
    partial void OnIIDSECCIONChanging(System.Nullable<int> value);
    partial void OnIIDSECCIONChanged();
    partial void OnBHABILITADOChanging(System.Nullable<int> value);
    partial void OnBHABILITADOChanged();
    #endregion
		
		public GradoSeccion()
		{
			this._Grado = default(EntityRef<Grado>);
			this._Seccion = default(EntityRef<Seccion>);
			this._Grado1 = default(EntityRef<Grado1>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int IID
		{
			get
			{
				return this._IID;
			}
			set
			{
				if ((this._IID != value))
				{
					this.OnIIDChanging(value);
					this.SendPropertyChanging();
					this._IID = value;
					this.SendPropertyChanged("IID");
					this.OnIIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IIDGRADO", DbType="Int")]
		public System.Nullable<int> IIDGRADO
		{
			get
			{
				return this._IIDGRADO;
			}
			set
			{
				if ((this._IIDGRADO != value))
				{
					if ((this._Grado.HasLoadedOrAssignedValue || this._Grado1.HasLoadedOrAssignedValue))
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnIIDGRADOChanging(value);
					this.SendPropertyChanging();
					this._IIDGRADO = value;
					this.SendPropertyChanged("IIDGRADO");
					this.OnIIDGRADOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IIDSECCION", DbType="Int")]
		public System.Nullable<int> IIDSECCION
		{
			get
			{
				return this._IIDSECCION;
			}
			set
			{
				if ((this._IIDSECCION != value))
				{
					if (this._Seccion.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnIIDSECCIONChanging(value);
					this.SendPropertyChanging();
					this._IIDSECCION = value;
					this.SendPropertyChanged("IIDSECCION");
					this.OnIIDSECCIONChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BHABILITADO", DbType="Int")]
		public System.Nullable<int> BHABILITADO
		{
			get
			{
				return this._BHABILITADO;
			}
			set
			{
				if ((this._BHABILITADO != value))
				{
					this.OnBHABILITADOChanging(value);
					this.SendPropertyChanging();
					this._BHABILITADO = value;
					this.SendPropertyChanged("BHABILITADO");
					this.OnBHABILITADOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Grado_GradoSeccion", Storage="_Grado", ThisKey="IIDGRADO", OtherKey="IIDGRADO", IsForeignKey=true)]
		public Grado Grado
		{
			get
			{
				return this._Grado.Entity;
			}
			set
			{
				Grado previousValue = this._Grado.Entity;
				if (((previousValue != value) 
							|| (this._Grado.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Grado.Entity = null;
						previousValue.GradoSeccion.Remove(this);
					}
					this._Grado.Entity = value;
					if ((value != null))
					{
						value.GradoSeccion.Add(this);
						this._IIDGRADO = value.IIDGRADO;
					}
					else
					{
						this._IIDGRADO = default(Nullable<int>);
					}
					this.SendPropertyChanged("Grado");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Seccion_GradoSeccion", Storage="_Seccion", ThisKey="IIDSECCION", OtherKey="IIDSECCION", IsForeignKey=true)]
		public Seccion Seccion
		{
			get
			{
				return this._Seccion.Entity;
			}
			set
			{
				Seccion previousValue = this._Seccion.Entity;
				if (((previousValue != value) 
							|| (this._Seccion.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Seccion.Entity = null;
						previousValue.GradoSeccion.Remove(this);
					}
					this._Seccion.Entity = value;
					if ((value != null))
					{
						value.GradoSeccion.Add(this);
						this._IIDSECCION = value.IIDSECCION;
					}
					else
					{
						this._IIDSECCION = default(Nullable<int>);
					}
					this.SendPropertyChanged("Seccion");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Grado1_GradoSeccion", Storage="_Grado1", ThisKey="IIDGRADO", OtherKey="IIDGRADO", IsForeignKey=true)]
		public Grado1 Grado1
		{
			get
			{
				return this._Grado1.Entity;
			}
			set
			{
				Grado1 previousValue = this._Grado1.Entity;
				if (((previousValue != value) 
							|| (this._Grado1.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Grado1.Entity = null;
						previousValue.GradoSeccion.Remove(this);
					}
					this._Grado1.Entity = value;
					if ((value != null))
					{
						value.GradoSeccion.Add(this);
						this._IIDGRADO = value.IIDGRADO;
					}
					else
					{
						this._IIDGRADO = default(Nullable<int>);
					}
					this.SendPropertyChanged("Grado1");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Grado")]
	public partial class Grado : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _IIDGRADO;
		
		private string _NOMBRE;
		
		private System.Nullable<int> _BHABILITADO;
		
		private EntitySet<GradoSeccion> _GradoSeccion;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIIDGRADOChanging(int value);
    partial void OnIIDGRADOChanged();
    partial void OnNOMBREChanging(string value);
    partial void OnNOMBREChanged();
    partial void OnBHABILITADOChanging(System.Nullable<int> value);
    partial void OnBHABILITADOChanged();
    #endregion
		
		public Grado()
		{
			this._GradoSeccion = new EntitySet<GradoSeccion>(new Action<GradoSeccion>(this.attach_GradoSeccion), new Action<GradoSeccion>(this.detach_GradoSeccion));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IIDGRADO", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int IIDGRADO
		{
			get
			{
				return this._IIDGRADO;
			}
			set
			{
				if ((this._IIDGRADO != value))
				{
					this.OnIIDGRADOChanging(value);
					this.SendPropertyChanging();
					this._IIDGRADO = value;
					this.SendPropertyChanged("IIDGRADO");
					this.OnIIDGRADOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NOMBRE", DbType="VarChar(100)")]
		public string NOMBRE
		{
			get
			{
				return this._NOMBRE;
			}
			set
			{
				if ((this._NOMBRE != value))
				{
					this.OnNOMBREChanging(value);
					this.SendPropertyChanging();
					this._NOMBRE = value;
					this.SendPropertyChanged("NOMBRE");
					this.OnNOMBREChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BHABILITADO", DbType="Int")]
		public System.Nullable<int> BHABILITADO
		{
			get
			{
				return this._BHABILITADO;
			}
			set
			{
				if ((this._BHABILITADO != value))
				{
					this.OnBHABILITADOChanging(value);
					this.SendPropertyChanging();
					this._BHABILITADO = value;
					this.SendPropertyChanged("BHABILITADO");
					this.OnBHABILITADOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Grado_GradoSeccion", Storage="_GradoSeccion", ThisKey="IIDGRADO", OtherKey="IIDGRADO")]
		public EntitySet<GradoSeccion> GradoSeccion
		{
			get
			{
				return this._GradoSeccion;
			}
			set
			{
				this._GradoSeccion.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_GradoSeccion(GradoSeccion entity)
		{
			this.SendPropertyChanging();
			entity.Grado = this;
		}
		
		private void detach_GradoSeccion(GradoSeccion entity)
		{
			this.SendPropertyChanging();
			entity.Grado = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Seccion")]
	public partial class Seccion : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _IIDSECCION;
		
		private string _NOMBRE;
		
		private System.Nullable<int> _BHABILITADO;
		
		private EntitySet<GradoSeccion> _GradoSeccion;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIIDSECCIONChanging(int value);
    partial void OnIIDSECCIONChanged();
    partial void OnNOMBREChanging(string value);
    partial void OnNOMBREChanged();
    partial void OnBHABILITADOChanging(System.Nullable<int> value);
    partial void OnBHABILITADOChanged();
    #endregion
		
		public Seccion()
		{
			this._GradoSeccion = new EntitySet<GradoSeccion>(new Action<GradoSeccion>(this.attach_GradoSeccion), new Action<GradoSeccion>(this.detach_GradoSeccion));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IIDSECCION", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int IIDSECCION
		{
			get
			{
				return this._IIDSECCION;
			}
			set
			{
				if ((this._IIDSECCION != value))
				{
					this.OnIIDSECCIONChanging(value);
					this.SendPropertyChanging();
					this._IIDSECCION = value;
					this.SendPropertyChanged("IIDSECCION");
					this.OnIIDSECCIONChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NOMBRE", DbType="VarChar(100)")]
		public string NOMBRE
		{
			get
			{
				return this._NOMBRE;
			}
			set
			{
				if ((this._NOMBRE != value))
				{
					this.OnNOMBREChanging(value);
					this.SendPropertyChanging();
					this._NOMBRE = value;
					this.SendPropertyChanged("NOMBRE");
					this.OnNOMBREChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BHABILITADO", DbType="Int")]
		public System.Nullable<int> BHABILITADO
		{
			get
			{
				return this._BHABILITADO;
			}
			set
			{
				if ((this._BHABILITADO != value))
				{
					this.OnBHABILITADOChanging(value);
					this.SendPropertyChanging();
					this._BHABILITADO = value;
					this.SendPropertyChanged("BHABILITADO");
					this.OnBHABILITADOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Seccion_GradoSeccion", Storage="_GradoSeccion", ThisKey="IIDSECCION", OtherKey="IIDSECCION")]
		public EntitySet<GradoSeccion> GradoSeccion
		{
			get
			{
				return this._GradoSeccion;
			}
			set
			{
				this._GradoSeccion.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_GradoSeccion(GradoSeccion entity)
		{
			this.SendPropertyChanging();
			entity.Seccion = this;
		}
		
		private void detach_GradoSeccion(GradoSeccion entity)
		{
			this.SendPropertyChanging();
			entity.Seccion = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Grado")]
	public partial class Grado1 : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _IIDGRADO;
		
		private string _NOMBRE;
		
		private System.Nullable<int> _BHABILITADO;
		
		private EntitySet<GradoSeccion> _GradoSeccion;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIIDGRADOChanging(int value);
    partial void OnIIDGRADOChanged();
    partial void OnNOMBREChanging(string value);
    partial void OnNOMBREChanged();
    partial void OnBHABILITADOChanging(System.Nullable<int> value);
    partial void OnBHABILITADOChanged();
    #endregion
		
		public Grado1()
		{
			this._GradoSeccion = new EntitySet<GradoSeccion>(new Action<GradoSeccion>(this.attach_GradoSeccion), new Action<GradoSeccion>(this.detach_GradoSeccion));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IIDGRADO", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int IIDGRADO
		{
			get
			{
				return this._IIDGRADO;
			}
			set
			{
				if ((this._IIDGRADO != value))
				{
					this.OnIIDGRADOChanging(value);
					this.SendPropertyChanging();
					this._IIDGRADO = value;
					this.SendPropertyChanged("IIDGRADO");
					this.OnIIDGRADOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NOMBRE", DbType="VarChar(100)")]
		public string NOMBRE
		{
			get
			{
				return this._NOMBRE;
			}
			set
			{
				if ((this._NOMBRE != value))
				{
					this.OnNOMBREChanging(value);
					this.SendPropertyChanging();
					this._NOMBRE = value;
					this.SendPropertyChanged("NOMBRE");
					this.OnNOMBREChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BHABILITADO", DbType="Int")]
		public System.Nullable<int> BHABILITADO
		{
			get
			{
				return this._BHABILITADO;
			}
			set
			{
				if ((this._BHABILITADO != value))
				{
					this.OnBHABILITADOChanging(value);
					this.SendPropertyChanging();
					this._BHABILITADO = value;
					this.SendPropertyChanged("BHABILITADO");
					this.OnBHABILITADOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Grado1_GradoSeccion", Storage="_GradoSeccion", ThisKey="IIDGRADO", OtherKey="IIDGRADO")]
		public EntitySet<GradoSeccion> GradoSeccion
		{
			get
			{
				return this._GradoSeccion;
			}
			set
			{
				this._GradoSeccion.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_GradoSeccion(GradoSeccion entity)
		{
			this.SendPropertyChanging();
			entity.Grado1 = this;
		}
		
		private void detach_GradoSeccion(GradoSeccion entity)
		{
			this.SendPropertyChanging();
			entity.Grado1 = null;
		}
	}
}
#pragma warning restore 1591
